using UnityEngine;

public class Cofre : MonoBehaviour
{
    public GameObject objetoReemplazo; // Objeto que reemplazar치 al cofre
    public Vector3 nuevasCoordenadas; // Coordenadas donde aparecer치 el nuevo objeto
    public Quaternion nuevaRotacion; // Rotaci칩n del nuevo objeto

    private void OnCollisionEnter(Collision other)
    {
        if (other.gameObject.CompareTag("Llave"))
        {
            // Destruir la llave
            Destroy(other.gameObject);

            // Instanciar el objeto de reemplazo en las coordenadas y rotaci칩n especificadas
            Instantiate(objetoReemplazo, nuevasCoordenadas, nuevaRotacion);

            // Destruir el cofre actual
            Destroy(gameObject);
        }
    }
}
